//! Putting pixels back: RGBA8 into the format a texture blob already holds.
//!
//! [`write`](super::write) can put a blob back into a pack, and [`decode`](super::decode) can turn a
//! blob into pixels. This is the half that was missing between them: nothing in this crate could
//! turn pixels back into a blob, so the write path could only ever put back bytes that had come out
//! of it. A tool that opens a texture and cannot replace it is a viewer.
//!
//! # What it does not change
//!
//! [`replace_pixels`] rewrites **only the image**, and that is what keeps it honest. The blob it
//! returns is the same length as the one it was given, byte for byte outside the mip chain and the
//! palette: the embedded `OldTextureInfo`, the `DebugName`, the dimensions, the format tag and
//! whatever else the compiler left in there arrive back untouched. Nothing has to be re-derived,
//! because nothing about the texture changes except what it looks like.
//!
//! That is also why a replacement must have the texture's own dimensions. Width and height live in
//! the embedded header, and the descriptor records where that header sits **as a distance from the
//! end of the blob** — so a differently-sized image means a differently-sized chain, which moves the
//! header without the descriptor saying so. Resizing is therefore not a harder version of this
//! function; it is a different one, and it would have to rewrite the descriptor too.
//!
//! What makes writing the chain safe at all is measured rather than assumed, and the obvious guess
//! is wrong. One might expect the image to end before `out_size − header_from_end`, since that is
//! where the descriptor starts counting backwards; over 2,323 real textures `ImageSize` runs **past**
//! that point in 2,113 of them, so those two fields are not nested. The invariant that does hold is
//! the one this module needs: the image, and the palette after it, end before the `DebugName` in
//! 2,323 of 2,323 — in 2,313 of them by exactly twelve bytes. So a write bounded by `ImageSize` and
//! the palette cannot reach the name or the header, and that is checked against a real pack rather
//! than argued.
//!
//! # The mip chain, from the file rather than from a rule
//!
//! A blob does not hold one image. It holds a chain, and `ImageSize` at header `+0x14` is its whole
//! length. Where the chain *stops* is not a constant and could not be guessed: measured over 2,423
//! textures (every one in the install's 30 car packs, plus 300 from a `VINYLS.BIN` for the
//! palettised tags), it ends at 8×8 in 1,491 of them, at 16×8 in 817, and 80 have no mips at all —
//! a 256×256 whose `ImageSize` is exactly its top level.
//!
//! So the chain is not assumed. Levels are generated by halving and laid down until they have
//! filled `ImageSize` **exactly**; over those same 2,423 textures that lands on the declared size
//! 2,423 times and is never off by a byte, which is the measurement this module rests on. A texture
//! whose chain does not land exactly is refused rather than written short — the levels below the
//! one that fits would be somebody else's pixels.
//!
//! # The formats, and what a re-encode costs
//!
//! Five tags, and the price is different for each. Measured by decoding every texture in the
//! install's 30 car packs and 120 of a `VINYLS.BIN`, re-encoding it, writing it back into the pack
//! and decoding it again — so the number below is what a *round trip through the file* costs, not
//! what an encoder scores on its own output:
//!
//! | tag | textures | came back identical | mean PSNR **over the ones that changed** |
//! |---|---|---|---|
//! | `0x20` BGRA | 436 | **436** | — nothing changed |
//! | `0x08`/`0x80`/`0x81` palettised | 120 | **120** | — nothing changed |
//! | `0x24` DXT3 | 742 | 378 | 44.9 dB over 364 |
//! | `0x22` DXT1 | 945 | 5 | 47.6 dB over 940 |
//!
//! The last column excludes the identical ones deliberately, and the first version of this table
//! did not — it gave every byte-identical texture a placeholder 99 dB and averaged those in, which
//! made DXT3 read **72.5 dB** when what a DXT3 re-encode actually costs is 44.9. The column beside
//! it was the giveaway: a format that came back identical 378 times out of 742 cannot also have a
//! mean error, and a number that improves as more textures are left untouched is measuring the
//! wrong thing.
//!
//! The two that come back **identical** are the two that can: a channel swap loses nothing, and an
//! image with no more colours than its tag populates is reproduced exactly by the median cut. The
//! S3TC pair cannot — the format holds two endpoints per 4×4 block, so it is lossy by construction
//! and no encoder returns another encoder's choice. Their numbers are also the *pessimistic* case:
//! this measurement re-encodes pixels that have already been through DXT once, whose block
//! artefacts do not line up with a fresh fit. A user's PNG has not paid that cost yet.
//!
//! Endpoints are fitted from the block's bounding box, inset, and then refined by least squares
//! against the indices they produce — keeping a refit only when it scores better, because least
//! squares minimises the continuous error and the answer still has to survive 5-6-5.
//!
//! The palettised cap is **not a guess about what the tag means** but the measurement in
//! [`decode`](super::decode): no `0x80` texture in the install's 24,071 ever indexes above 15, and
//! no `0x81` in 1,840 above 63. Writing an index past it would make this the first file in the game
//! to do so.
//!
//! # What a replacement costs the pack
//!
//! A blob whose length does not change can still recompress to something bigger, so the in-place
//! path is not guaranteed even here. Over the same 2,243 textures, **1,975 fit where they lay and
//! 268 needed [`relocate`](super::write::relocate)** — so a caller should try the cheap path and
//! fall back rather than choosing one up front.
//!
//! The DXT encoders score their candidates with [`dxt::palette_from`](super::dxt::palette_from) and
//! [`dxt::build_alpha_table`](super::dxt::build_alpha_table) — the decoder's own functions, not a
//! second copy of them. Two copies agree until one is tuned; one copy means a block round-trips
//! because the same arithmetic wrote and read it.

use super::decode::{self, fmt};
use super::directory::TpkEntry;
use super::dxt;
use crate::error::{NfsError, NfsResult};

/// Bytes per pixel in the RGBA8 input.
const RGBA: usize = 4;

/// The alpha below which a DXT1 pixel is written as the punch-through slot rather than a colour.
///
/// DXT1 carries one bit of alpha and nothing between, so a threshold is unavoidable; 128 is the
/// midpoint, which is what every S3TC encoder uses and what the format's own 1-bit reading implies.
const ALPHA_CUT: u8 = 128;

/// How many times an endpoint pair is refitted against the indices it produced.
///
/// Two, because the third almost never moves it: refinement stops early anyway when a round returns
/// the same pair or a worse one, and the loop below is written so that a round that does not improve
/// the block is discarded rather than kept.
const REFINE: usize = 2;

/// Re-encode `rgba` into the format `blob` already holds, returning a blob of the same length.
///
/// `blob` is what [`blob_of`](super::write::blob_of) hands out — one texture's decompressed stream —
/// and the return value is the shape [`replace_blob`](super::write::replace_blob) and
/// [`relocate`](super::write::relocate) take back. The image must have the texture's own dimensions;
/// see the module docs for why that is a different function rather than a stricter one.
///
/// # Errors
/// - The embedded header is not where the descriptor says, or fails its own hash self-check — the
///   same refusal [`decode`](super::decode) makes, so a texture that cannot be read cannot be
///   written either.
/// - The image's dimensions are not the texture's, or `rgba` is not `width * height * 4` bytes.
/// - The pixel format is one this crate does not encode.
/// - The declared `ImageSize` is not exactly a prefix of the halving mip chain.
pub fn replace_pixels(
    blob: &[u8],
    entry: &TpkEntry,
    rgba: &[u8],
    width: u32,
    height: u32,
) -> NfsResult<Vec<u8>> {
    // The blob must be exactly the length the descriptor declares, and "at least" is not good
    // enough. [`relocate`](super::write::relocate) writes the replacement's length back into the
    // descriptor's `out_size` while leaving `header_from_end` alone, and the header's position is
    // the difference of those two — so a blob one byte longer than declared would relocate into a
    // pack whose header is looked for one byte off, and the texture would decode as noise.
    //
    // It cannot happen with a blob this crate handed out: over 2,423 real textures,
    // [`blob_of`](super::write::blob_of) returns exactly `out_size` bytes 2,423 times, longer
    // never and shorter never. The check is here because the input is a caller's, not because the
    // measurement is in doubt.
    let out_size = entry.out_size as usize;
    if blob.len() != out_size {
        return Err(NfsError::BufferSizeMismatch {
            detail: "a blob to re-encode must be exactly the length its descriptor declares",
        });
    }

    // The header is found exactly as the decoder finds it, and refused exactly as the decoder
    // refuses it. A texture the reader skips is not one the writer should have an opinion about.
    let p = decode::header_at(out_size, entry.header_from_end as usize)?;
    let hdr = blob
        .get(p..p + decode::HEADER_LEN)
        .ok_or(NfsError::CorruptArchive { detail: "TPK header out of range" })?;
    if u32::from_le_bytes([hdr[0], hdr[1], hdr[2], hdr[3]]) != entry.hash.0 {
        return Err(NfsError::CorruptArchive { detail: "TPK header hash mismatch" });
    }
    let w = u16::from_le_bytes([hdr[32], hdr[33]]) as usize;
    let h = u16::from_le_bytes([hdr[34], hdr[35]]) as usize;
    let comp = hdr[38];
    if w == 0 || h == 0 || w > decode::MAX_DIM || h > decode::MAX_DIM {
        return Err(NfsError::CorruptArchive { detail: "TPK texture dimensions out of range" });
    }
    if w != width as usize || h != height as usize {
        return Err(NfsError::BufferSizeMismatch {
            detail: "a replacement image must have the texture's own dimensions",
        });
    }
    if rgba.len() != w.saturating_mul(h).saturating_mul(RGBA) {
        return Err(NfsError::BufferSizeMismatch {
            detail: "replacement pixels are not width * height * 4 bytes",
        });
    }

    let image_size = u32::from_le_bytes([hdr[20], hdr[21], hdr[22], hdr[23]]) as usize;
    let levels = chain(w, h, comp, image_size)?;

    // The palette is rebuilt before any level is written, because every level indexes into it.
    let mut out = blob.to_vec();
    let palette = if decode::is_palettised(comp) {
        let top = decode::level_size(w, h, comp)
            .ok_or(NfsError::NotImplemented { feature: "TPK pixel format" })?;
        let at = decode::palette_at(hdr, top)?;
        let colours = quantise(rgba, palette_cap(comp));
        let region = out
            .get_mut(at..at + decode::PALETTE_BYTES)
            .ok_or(NfsError::BufferSizeMismatch { detail: "TPK palette out of range" })?;
        // Entries past the ones this image needs keep the bytes they had. They are not read — no
        // index reaches them — and rewriting them would put a diff where there is no change.
        for (slot, c) in region.chunks_exact_mut(4).zip(colours.iter()) {
            slot.copy_from_slice(&[c[2], c[1], c[0], c[3]]); // stored B,G,R,A
        }
        Some(colours)
    } else {
        None
    };

    // Each level is the previous one halved, so the pyramid is built once and consumed as it goes.
    let mut level = rgba.to_vec();
    let mut cache = std::collections::HashMap::new();
    for (i, lv) in levels.iter().enumerate() {
        if i > 0 {
            let prev = levels
                .get(i - 1)
                .ok_or(NfsError::CorruptArchive { detail: "TPK mip chain" })?;
            level = downsample(&level, prev.w, prev.h, lv.w, lv.h);
        }
        let dst = out
            .get_mut(lv.at..lv.at + lv.len)
            .ok_or(NfsError::BufferSizeMismatch { detail: "TPK mip chain runs past the blob" })?;
        match comp {
            fmt::RGBA8888 => write_bgra(&level, dst),
            fmt::DXT1 => write_dxt(&level, lv.w, lv.h, dst, Dxt::One),
            fmt::DXT3 => write_dxt(&level, lv.w, lv.h, dst, Dxt::Three),
            fmt::DXT5 => write_dxt(&level, lv.w, lv.h, dst, Dxt::Five),
            c if decode::is_palettised(c) => {
                let pal = palette
                    .as_deref()
                    .ok_or(NfsError::NotImplemented { feature: "TPK pixel format" })?;
                write_indices(&level, pal, dst, &mut cache);
            }
            _ => return Err(NfsError::NotImplemented { feature: "TPK pixel format" }),
        }
    }
    Ok(out)
}

/// How many palette entries a tag populates.
///
/// Measured, not read off the number — see [`decode`](super::decode)'s table. `0x80` never indexes
/// above 15 in 24,071 textures and `0x81` never above 63 in 1,840, where `0x08` reaches 255.
const fn palette_cap(comp: u8) -> usize {
    match comp {
        fmt::P8_16 => 16,
        fmt::P8_64 => 64,
        _ => 256,
    }
}

/// One level of the chain: its dimensions, where it starts in the blob, and how many bytes it is.
struct Level {
    w: usize,
    h: usize,
    at: usize,
    len: usize,
}

/// Lay out the mip chain that fills `image_size` exactly.
///
/// The chain halves (never below 1) and stops when the declared size is used up. It is an error for
/// the last level to overshoot or for the chain to run out with bytes left over: either means this
/// texture's chain is not the one the arithmetic describes, and writing it would put a level's
/// pixels where the next level's are read from.
fn chain(width: usize, height: usize, comp: u8, image_size: usize) -> NfsResult<Vec<Level>> {
    let mut levels = Vec::new();
    let (mut w, mut h) = (width, height);
    let mut at = 0usize;
    while at < image_size {
        let len = decode::level_size(w, h, comp)
            .ok_or(NfsError::NotImplemented { feature: "TPK pixel format" })?;
        if at + len > image_size {
            return Err(NfsError::CorruptArchive {
                detail: "TPK mip chain overshoots the declared ImageSize",
            });
        }
        levels.push(Level { w, h, at, len });
        at += len;
        if w == 1 && h == 1 {
            break;
        }
        w = (w / 2).max(1);
        h = (h / 2).max(1);
    }
    if at != image_size {
        return Err(NfsError::CorruptArchive {
            detail: "TPK ImageSize is not a whole number of mip levels",
        });
    }
    // A chain of nothing satisfies the arithmetic above — zero levels fill zero bytes exactly — and
    // would let a header declaring `ImageSize == 0` come back `Ok` with no pixels written at all.
    // For a palettised tag that is worse than doing nothing: the palette is rewritten before the
    // levels are, so the old indices would be left pointing into a new set of colours.
    if levels.is_empty() {
        return Err(NfsError::CorruptArchive { detail: "TPK ImageSize declares no image at all" });
    }
    Ok(levels)
}

/// Halve an RGBA8 image with a box filter.
///
/// Straight per-channel averaging, alpha included and not premultiplied. That matches how the game's
/// own chains look — a `_MASK`'s levels average its alpha the same way — and it keeps a fully
/// transparent region transparent, which premultiplying would not do any better here.
fn downsample(src: &[u8], sw: usize, sh: usize, dw: usize, dh: usize) -> Vec<u8> {
    let mut out = vec![0u8; dw * dh * RGBA];
    for y in 0..dh {
        for x in 0..dw {
            // Odd dimensions clamp rather than wrap, so the last column is sampled twice instead
            // of the first being folded into it.
            let x0 = (x * 2).min(sw - 1);
            let x1 = (x * 2 + 1).min(sw - 1);
            let y0 = (y * 2).min(sh - 1);
            let y1 = (y * 2 + 1).min(sh - 1);
            let mut acc = [0u32; RGBA];
            for (sx, sy) in [(x0, y0), (x1, y0), (x0, y1), (x1, y1)] {
                let o = (sy * sw + sx) * RGBA;
                if let Some(px) = src.get(o..o + RGBA) {
                    for k in 0..RGBA {
                        acc[k] += px[k] as u32;
                    }
                }
            }
            let o = (y * dw + x) * RGBA;
            if let Some(dst) = out.get_mut(o..o + RGBA) {
                for k in 0..RGBA {
                    dst[k] = (acc[k] / 4) as u8;
                }
            }
        }
    }
    out
}

/// RGBA8 → the `0x20` format's B,G,R,A. The one arm that loses nothing.
fn write_bgra(rgba: &[u8], dst: &mut [u8]) {
    for (d, s) in dst.chunks_exact_mut(4).zip(rgba.chunks_exact(4)) {
        d.copy_from_slice(&[s[2], s[1], s[0], s[3]]);
    }
}

/// Which S3TC variant a block is being written as.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Dxt {
    One,
    Three,
    Five,
}

impl Dxt {
    const fn block_bytes(self) -> usize {
        match self {
            Dxt::One => 8,
            _ => 16,
        }
    }
}

/// Encode an RGBA8 level as DXT1/3/5 blocks.
fn write_dxt(rgba: &[u8], w: usize, h: usize, dst: &mut [u8], kind: Dxt) {
    let bw = w.div_ceil(4);
    let bh = h.div_ceil(4);
    let stride = kind.block_bytes();
    for by in 0..bh {
        for bx in 0..bw {
            let px = gather(rgba, w, h, bx, by);
            let off = (by * bw + bx) * stride;
            let Some(block) = dst.get_mut(off..off + stride) else { continue };
            match kind {
                Dxt::One => {
                    // DXT1 is the only one whose colour block carries alpha, so it is the only one
                    // that ever asks for the punch-through reading.
                    let punch = px.iter().any(|p| p[3] < ALPHA_CUT);
                    block.copy_from_slice(&colour_block(&px, punch));
                }
                Dxt::Three => {
                    block[..8].copy_from_slice(&alpha_nibbles(&px));
                    block[8..].copy_from_slice(&colour_block(&px, false));
                }
                Dxt::Five => {
                    block[..8].copy_from_slice(&alpha_interpolated(&px));
                    block[8..].copy_from_slice(&colour_block(&px, false));
                }
            }
        }
    }
}

/// The 4×4 pixels of one block, edge-clamped where the image ends.
///
/// Clamping rather than zero-filling: the decoder ignores the pixels past the edge, but the encoder
/// does not — a block padded with transparent black would fit its endpoints to a colour no visible
/// pixel has, and the visible ones would pay for it.
fn gather(rgba: &[u8], w: usize, h: usize, bx: usize, by: usize) -> [[u8; 4]; 16] {
    let mut px = [[0u8; 4]; 16];
    for row in 0..4 {
        for col in 0..4 {
            let x = (bx * 4 + col).min(w.saturating_sub(1));
            let y = (by * 4 + row).min(h.saturating_sub(1));
            let o = (y * w + x) * RGBA;
            if let Some(s) = rgba.get(o..o + RGBA) {
                px[row * 4 + col].copy_from_slice(s);
            }
        }
    }
    px
}

/// DXT3's alpha half: one 4-bit value per pixel, low nibble first.
fn alpha_nibbles(px: &[[u8; 4]; 16]) -> [u8; 8] {
    let mut out = [0u8; 8];
    for (i, p) in px.iter().enumerate() {
        // The decoder expands a nibble as `(a4 << 4) | a4`, i.e. a4 * 17, so the nearest 4-bit
        // value is a rounded fifteenth rather than a truncated one.
        let a4 = ((p[3] as u16 * 15 + 127) / 255) as u8;
        if i % 2 == 0 {
            out[i / 2] |= a4;
        } else {
            out[i / 2] |= a4 << 4;
        }
    }
    out
}

/// DXT5's alpha half: two endpoints and sixteen 3-bit indices into the table between them.
fn alpha_interpolated(px: &[[u8; 4]; 16]) -> [u8; 8] {
    let mut lo = 255u8;
    let mut hi = 0u8;
    for p in px {
        lo = lo.min(p[3]);
        hi = hi.max(p[3]);
    }
    // `a0 > a1` selects the eight-value table, which spends both endpoints on real alphas; the
    // other reading gives up two slots to a hard 0 and 255 that min/max already cover.
    let (a0, a1) = (hi, lo);
    let table = dxt::build_alpha_table(a0, a1);
    let mut bits: u64 = 0;
    for (i, p) in px.iter().enumerate() {
        let mut best = 0usize;
        let mut best_err = u32::MAX;
        for (k, &v) in table.iter().enumerate() {
            let d = (v as i32 - p[3] as i32).unsigned_abs();
            if d < best_err {
                best_err = d;
                best = k;
            }
        }
        bits |= (best as u64) << (3 * i);
    }
    let mut out = [0u8; 8];
    out[0] = a0;
    out[1] = a1;
    out[2..8].copy_from_slice(&bits.to_le_bytes()[..6]);
    out
}

/// The eight bytes of a BC1-style colour block: two RGB565 endpoints and sixteen 2-bit indices.
///
/// `punch` asks for the three-colour reading, whose fourth slot is transparent — DXT1's only way of
/// saying a pixel has no colour at all.
fn colour_block(px: &[[u8; 4]; 16], punch: bool) -> [u8; 8] {
    let mut lit = [true; 16];
    if punch {
        for (m, p) in lit.iter_mut().zip(px.iter()) {
            *m = p[3] >= ALPHA_CUT;
        }
    }
    if !lit.iter().any(|m| *m) {
        // Every pixel transparent. `c0 == c1` is the three-colour reading, and index 3 is its
        // transparent slot, so this is a block that decodes to nothing at all.
        let mut out = [0u8; 8];
        out[4..8].copy_from_slice(&u32::MAX.to_le_bytes());
        return out;
    }

    // One starting pair, inset, and the refinement below does the rest. All three of the obvious
    // choices were measured over the install's DXT1 textures, decoded and re-encoded, scoring only
    // the ones that came back changed: the plain bounding box gives 47.3 dB, insetting a sixteenth
    // gives **47.6**, and starting from both and keeping the better-scoring one gives 47.5 — worse
    // than the better of its own two inputs, because the choice is made on the starting pair and it
    // is the refinement that decides the outcome. So the extra candidate is not here: it cost code
    // and a tenth of a decibel.
    let (mut c0, mut c1) = range_fit(px, &lit, punch, 1.0 / 16.0);
    let mut best = block_error(px, &lit, c0, c1, punch);
    for _ in 0..REFINE {
        let idx = assign(px, &lit, c0, c1, punch);
        let Some((n0, n1)) = refit(px, &lit, &idx, c0, c1, punch) else { break };
        if (n0, n1) == (c0, c1) {
            break;
        }
        let err = block_error(px, &lit, n0, n1, punch);
        // A refit that scores worse is thrown away rather than kept: least squares minimises the
        // continuous error, and the endpoints it hands back still have to survive 5-6-5.
        if err >= best {
            break;
        }
        c0 = n0;
        c1 = n1;
        best = err;
    }

    let idx = assign(px, &lit, c0, c1, punch);
    let mut bits: u32 = 0;
    for (i, &k) in idx.iter().enumerate() {
        bits |= (k as u32) << (2 * i);
    }
    let mut out = [0u8; 8];
    out[0..2].copy_from_slice(&c0.to_le_bytes());
    out[2..4].copy_from_slice(&c1.to_le_bytes());
    out[4..8].copy_from_slice(&bits.to_le_bytes());
    out
}

/// Endpoints from the block's bounding box, optionally pulled in by `inset` of its range.
///
/// The extremes of a block are often one pixel each, and spending both endpoints on them leaves the
/// interpolated pair to cover everything else; pulling in trades error at the ends for less in the
/// middle, where most of the pixels are. Which of those is the better trade depends on the block, so
/// [`colour_block`] asks for both and keeps the one that scores.
fn range_fit(px: &[[u8; 4]; 16], lit: &[bool; 16], punch: bool, inset: f32) -> (u16, u16) {
    let mut lo = [255u8; 3];
    let mut hi = [0u8; 3];
    for (p, _) in px.iter().zip(lit.iter()).filter(|(_, m)| **m) {
        for k in 0..3 {
            lo[k] = lo[k].min(p[k]);
            hi[k] = hi[k].max(p[k]);
        }
    }
    let mut a = [0f32; 3];
    let mut b = [0f32; 3];
    for k in 0..3 {
        let pull = (hi[k] as f32 - lo[k] as f32) * inset;
        a[k] = (hi[k] as f32 - pull).clamp(0.0, 255.0);
        b[k] = (lo[k] as f32 + pull).clamp(0.0, 255.0);
    }
    order(pack565(a), pack565(b), punch)
}

/// Put a candidate pair the way round the reading needs.
///
/// The 4-colour reading is `c0 > c1` and the 3-colour one `c0 <= c1`; the decoder chooses between
/// them by that comparison alone. Indices are assigned *after* this, so a swap costs nothing —
/// there is nothing to remap.
const fn order(x: u16, y: u16, punch: bool) -> (u16, u16) {
    if punch == (x > y) {
        (y, x)
    } else {
        (x, y)
    }
}

/// Quantise a float RGB triple to 5-6-5.
fn pack565(c: [f32; 3]) -> u16 {
    let q = |v: f32, bits: u32| -> u16 {
        let max = ((1u16 << bits) - 1) as f32;
        ((v / 255.0 * max) + 0.5).clamp(0.0, max) as u16
    };
    (q(c[0], 5) << 11) | (q(c[1], 6) << 5) | q(c[2], 5)
}

/// Nearest palette entry for every pixel, with the transparent slot reserved for what asked for it.
fn assign(px: &[[u8; 4]; 16], lit: &[bool; 16], c0: u16, c1: u16, punch: bool) -> [u8; 16] {
    let (pal, three) = dxt::palette_from(c0, c1, punch);
    let usable = if three { 3 } else { 4 };
    let mut out = [0u8; 16];
    for (i, p) in px.iter().enumerate() {
        if !lit[i] {
            out[i] = 3; // the transparent slot; only reachable in the three-colour reading
            continue;
        }
        let mut best = 0usize;
        let mut best_err = u32::MAX;
        for (k, entry) in pal.iter().enumerate().take(usable) {
            let e = rgb_error(*entry, *p);
            if e < best_err {
                best_err = e;
                best = k;
            }
        }
        out[i] = best as u8;
    }
    out
}

/// Squared RGB distance between a palette entry and a pixel.
fn rgb_error(e: [u8; 3], p: [u8; 4]) -> u32 {
    let mut sum = 0u32;
    for k in 0..3 {
        let d = (e[k] as i32 - p[k] as i32).unsigned_abs();
        sum += d * d;
    }
    sum
}

/// The block's total error under a candidate pair, counting only the pixels that carry colour.
fn block_error(px: &[[u8; 4]; 16], lit: &[bool; 16], c0: u16, c1: u16, punch: bool) -> u32 {
    let (pal, three) = dxt::palette_from(c0, c1, punch);
    let usable = if three { 3 } else { 4 };
    let mut total = 0u32;
    for (i, p) in px.iter().enumerate() {
        if !lit[i] {
            continue;
        }
        let mut best = u32::MAX;
        for entry in pal.iter().take(usable) {
            best = best.min(rgb_error(*entry, *p));
        }
        total = total.saturating_add(best);
    }
    total
}

/// Least-squares refit: given which slot each pixel chose, where should the two endpoints be?
///
/// Each index carries a known fraction of the way from one endpoint to the other (0, ⅓, ⅔, 1 in the
/// four-colour reading; 0, ½, 1 in the three-colour one), so the pixels and their fractions are an
/// over-determined pair of lines and the endpoints are what fits them. Returns `None` when the
/// system is degenerate — every pixel on one slot — because there is nothing to solve for then.
fn refit(
    px: &[[u8; 4]; 16],
    lit: &[bool; 16],
    idx: &[u8; 16],
    c0: u16,
    c1: u16,
    punch: bool,
) -> Option<(u16, u16)> {
    let (_, three) = dxt::palette_from(c0, c1, punch);
    let (mut aa, mut ab, mut bb) = (0f32, 0f32, 0f32);
    let mut ax = [0f32; 3];
    let mut bx = [0f32; 3];
    for (i, p) in px.iter().enumerate() {
        if !lit[i] {
            continue;
        }
        let Some(t) = fraction(idx[i], three) else { continue };
        let s = 1.0 - t;
        aa += s * s;
        ab += s * t;
        bb += t * t;
        for k in 0..3 {
            ax[k] += s * p[k] as f32;
            bx[k] += t * p[k] as f32;
        }
    }
    let det = aa * bb - ab * ab;
    if det.abs() < 1e-4 {
        return None;
    }
    let mut a = [0f32; 3];
    let mut b = [0f32; 3];
    for k in 0..3 {
        a[k] = ((bb * ax[k] - ab * bx[k]) / det).clamp(0.0, 255.0);
        b[k] = ((aa * bx[k] - ab * ax[k]) / det).clamp(0.0, 255.0);
    }
    Some(order(pack565(a), pack565(b), punch))
}

/// How far along the line from `c0` to `c1` a slot sits, or `None` for the transparent one.
fn fraction(idx: u8, three: bool) -> Option<f32> {
    Some(match (idx, three) {
        (0, _) => 0.0,
        (1, _) => 1.0,
        (2, false) => 1.0 / 3.0,
        (3, false) => 2.0 / 3.0,
        (2, true) => 0.5,
        _ => return None,
    })
}

/// Map every pixel to its nearest palette entry.
///
/// The cache is what makes this affordable: a 512² vinyl is 262,144 pixels against up to 256
/// entries, and the images these tags carry are flat artwork whose distinct colours number in the
/// hundreds, not the hundreds of thousands.
fn write_indices(
    rgba: &[u8],
    palette: &[[u8; 4]],
    dst: &mut [u8],
    cache: &mut std::collections::HashMap<[u8; 4], u8>,
) {
    for (d, s) in dst.iter_mut().zip(rgba.chunks_exact(4)) {
        let key = [s[0], s[1], s[2], s[3]];
        *d = *cache.entry(key).or_insert_with(|| nearest(palette, key));
    }
}

/// The palette entry closest to one colour, alpha counted alongside the channels.
fn nearest(palette: &[[u8; 4]], c: [u8; 4]) -> u8 {
    let mut best = 0usize;
    let mut best_err = u32::MAX;
    for (i, e) in palette.iter().enumerate() {
        let mut sum = 0u32;
        for k in 0..4 {
            let d = (e[k] as i32 - c[k] as i32).unsigned_abs();
            sum += d * d;
        }
        if sum < best_err {
            best_err = sum;
            best = i;
        }
    }
    best as u8
}

/// Build a palette of at most `cap` colours by median cut.
///
/// Median cut rather than a fixed cube: these images are flat artwork — a flag, a wordmark, a
/// stripe — where the colours that matter occupy a small part of the space and a uniform grid would
/// spend most of its entries on emptiness. An image with few enough distinct colours skips the cut
/// entirely and is reproduced exactly.
fn quantise(rgba: &[u8], cap: usize) -> Vec<[u8; 4]> {
    let mut counts: std::collections::HashMap<[u8; 4], u32> = std::collections::HashMap::new();
    for px in rgba.chunks_exact(4) {
        *counts.entry([px[0], px[1], px[2], px[3]]).or_insert(0) += 1;
    }
    let mut colours: Vec<([u8; 4], u32)> = counts.into_iter().collect();
    // Iteration order of a HashMap is not stable across runs, and a palette that comes out in a
    // different order writes different indices for the same image. Sorting is what makes two runs
    // over one PNG produce the same bytes.
    colours.sort_unstable();
    if colours.is_empty() {
        return vec![[0, 0, 0, 0]];
    }
    if colours.len() <= cap {
        return colours.into_iter().map(|(c, _)| c).collect();
    }

    // Boxes as ranges over `colours`; split the widest until there are `cap` of them.
    let mut boxes: Vec<(usize, usize)> = vec![(0, colours.len())];
    while boxes.len() < cap {
        let Some(pick) = boxes
            .iter()
            .enumerate()
            .filter(|(_, (s, e))| e - s > 1)
            .max_by_key(|(_, (s, e))| spread(&colours[*s..*e]).0)
            .map(|(i, _)| i)
        else {
            break;
        };
        let (s, e) = boxes[pick];
        let (_, channel) = spread(&colours[s..e]);
        colours[s..e].sort_unstable_by_key(|(c, _)| c[channel]);
        // Split at the weighted median, so a box holding one dominant colour and a long tail does
        // not hand the tail an entry of its own while the dominant one shares.
        let total: u64 = colours[s..e].iter().map(|(_, n)| *n as u64).sum();
        let mut acc = 0u64;
        let mut mid = s + 1;
        for (i, (_, n)) in colours[s..e].iter().enumerate() {
            acc += *n as u64;
            if acc * 2 >= total {
                mid = (s + i + 1).min(e - 1).max(s + 1);
                break;
            }
        }
        boxes[pick] = (s, mid);
        boxes.push((mid, e));
    }

    boxes
        .iter()
        .filter(|(s, e)| e > s)
        .map(|(s, e)| average(&colours[*s..*e]))
        .collect()
}

/// The widest channel of a set of colours, and how wide it is.
fn spread(set: &[([u8; 4], u32)]) -> (u32, usize) {
    let mut lo = [255u8; 4];
    let mut hi = [0u8; 4];
    for (c, _) in set {
        for k in 0..4 {
            lo[k] = lo[k].min(c[k]);
            hi[k] = hi[k].max(c[k]);
        }
    }
    let mut best = (0u32, 0usize);
    for k in 0..4 {
        let d = (hi[k] - lo[k]) as u32;
        if d > best.0 {
            best = (d, k);
        }
    }
    best
}

/// A box's representative colour: the average of what is in it, weighted by how often it occurs.
fn average(set: &[([u8; 4], u32)]) -> [u8; 4] {
    let mut acc = [0u64; 4];
    let mut n = 0u64;
    for (c, count) in set {
        for k in 0..4 {
            acc[k] += c[k] as u64 * *count as u64;
        }
        n += *count as u64;
    }
    let mut out = [0u8; 4];
    if n == 0 {
        return out;
    }
    for k in 0..4 {
        out[k] = (acc[k] / n) as u8;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::AssetHash;

    /// A blob shaped the way a real one is: a mip chain, then a palette if the tag wants one, then
    /// the `DebugName` and the embedded header at the distance the descriptor declares.
    fn blob(w: usize, h: usize, comp: u8, levels: usize) -> (Vec<u8>, TpkEntry) {
        let mut image_size = 0usize;
        let (mut lw, mut lh) = (w, h);
        for _ in 0..levels {
            image_size += decode::level_size(lw, lh, comp).expect("sizeable");
            lw = (lw / 2).max(1);
            lh = (lh / 2).max(1);
        }
        let palette = if decode::is_palettised(comp) { decode::PALETTE_BYTES } else { 0 };
        let header_from_end = 0x100usize;
        // Everything after the image: palette, then enough room for the header the descriptor
        // points at, which sits `header_from_end - 0x88` before the end.
        let out_size = image_size + palette + header_from_end;
        let p = out_size - header_from_end + 0x64 + 0x24;

        let mut buf = vec![0u8; out_size];
        let hash = 0x1234_5678u32;
        buf[p..p + 4].copy_from_slice(&hash.to_le_bytes());
        // ImagePlacement / PalettePlacement: only their difference is read, so 0 and image_size+64
        // put the palette where the decoder looks for it.
        buf[p + 0x0C..p + 0x10].copy_from_slice(&0u32.to_le_bytes());
        buf[p + 0x10..p + 0x14].copy_from_slice(&((image_size + 64) as u32).to_le_bytes());
        buf[p + 0x14..p + 0x18].copy_from_slice(&(image_size as u32).to_le_bytes());
        buf[p + 0x18..p + 0x1C].copy_from_slice(&(decode::PALETTE_BYTES as u32).to_le_bytes());
        buf[p + 32..p + 34].copy_from_slice(&(w as u16).to_le_bytes());
        buf[p + 34..p + 36].copy_from_slice(&(h as u16).to_le_bytes());
        buf[p + 38] = comp;

        let entry = TpkEntry {
            hash: AssetHash(hash),
            abs_offset: 0,
            size: 0,
            out_size: out_size as u32,
            header_from_end: header_from_end as u32,
        };
        (buf, entry)
    }

    /// A recognisable test image: red, green, blue and transparent quadrants.
    fn quadrants(w: usize, h: usize) -> Vec<u8> {
        let mut px = vec![0u8; w * h * 4];
        for y in 0..h {
            for x in 0..w {
                let c = match (x < w / 2, y < h / 2) {
                    (true, true) => [220, 20, 20, 255],
                    (false, true) => [20, 200, 20, 255],
                    (true, false) => [20, 20, 210, 255],
                    (false, false) => [10, 10, 10, 0],
                };
                px[(y * w + x) * 4..(y * w + x) * 4 + 4].copy_from_slice(&c);
            }
        }
        px
    }

    #[test]
    fn bgra_is_exact() {
        let (buf, entry) = blob(16, 16, fmt::RGBA8888, 3);
        let px = quadrants(16, 16);
        let out = replace_pixels(&buf, &entry, &px, 16, 16).expect("encode");
        assert_eq!(out.len(), buf.len(), "a replacement must not resize the blob");
        // The top mip, read back the way the decoder reads it.
        let back: Vec<u8> = out[..16 * 16 * 4]
            .chunks_exact(4)
            .flat_map(|c| [c[2], c[1], c[0], c[3]])
            .collect();
        assert_eq!(back, px, "the one format that loses nothing must lose nothing");
    }

    #[test]
    fn only_the_image_changes() {
        let (mut buf, entry) = blob(32, 32, fmt::DXT1, 4);
        // Fill the slack between the chain and the header with something recognisable. Not the
        // header itself: its width and height are 32, whose high bytes are zero, so writing over
        // the zeroes there would be the test breaking the fixture rather than the code.
        let image_size = 32 * 32 / 2 + 16 * 16 / 2 + 8 * 8 / 2 + 4 * 4 / 2;
        let p = decode::header_at(entry.out_size as usize, entry.header_from_end as usize).unwrap();
        for (i, b) in buf.iter_mut().enumerate().take(p - 0x18).skip(image_size) {
            *b = (i % 251) as u8;
        }
        let out = replace_pixels(&buf, &entry, &quadrants(32, 32), 32, 32).expect("encode");
        assert_eq!(out.len(), buf.len());
        assert_eq!(&out[image_size..], &buf[image_size..], "nothing outside the chain may move");
        assert_ne!(&out[..image_size], &buf[..image_size], "the chain must have been written");
    }

    #[test]
    fn dxt1_round_trips_close_enough_to_see() {
        let (buf, entry) = blob(32, 32, fmt::DXT1, 1);
        let px = quadrants(32, 32);
        let out = replace_pixels(&buf, &entry, &px, 32, 32).expect("encode");
        let back = dxt::decode_dxt1(&out[..32 * 32 / 2], 32, 32);
        // Flat quadrants are the easy case for a block encoder; anything more than a couple of
        // levels off means the endpoints or the indices are wrong, not that DXT is lossy.
        for (i, (a, b)) in back.chunks_exact(4).zip(px.chunks_exact(4)).enumerate() {
            if b[3] < ALPHA_CUT {
                assert_eq!(a[3], 0, "pixel {i} should have gone to the transparent slot");
                continue;
            }
            for k in 0..3 {
                let d = (a[k] as i32 - b[k] as i32).abs();
                assert!(d <= 8, "pixel {i} channel {k}: {} vs {} ", a[k], b[k]);
            }
        }
    }

    #[test]
    fn dxt5_keeps_a_gradient_of_alpha() {
        let (buf, entry) = blob(16, 16, fmt::DXT5, 1);
        let mut px = vec![0u8; 16 * 16 * 4];
        for (i, p) in px.chunks_exact_mut(4).enumerate() {
            p.copy_from_slice(&[180, 90, 40, (i * 255 / 255).min(255) as u8]);
        }
        let out = replace_pixels(&buf, &entry, &px, 16, 16).expect("encode");
        let back = dxt::decode_dxt5(&out[..16 * 16], 16, 16);
        for (i, (a, b)) in back.chunks_exact(4).zip(px.chunks_exact(4)).enumerate() {
            let d = (a[3] as i32 - b[3] as i32).abs();
            assert!(d <= 12, "alpha at {i}: {} vs {}", a[3], b[3]);
        }
    }

    #[test]
    fn a_palettised_image_of_few_colours_is_exact() {
        let (buf, entry) = blob(16, 16, fmt::P8_16, 1);
        let px = quadrants(16, 16); // four distinct colours, and the cap is sixteen
        let out = replace_pixels(&buf, &entry, &px, 16, 16).expect("encode");

        let pal_at = 16 * 16 + 64;
        let palette = &out[pal_at..pal_at + decode::PALETTE_BYTES];
        for (i, p) in out[..16 * 16].iter().enumerate() {
            let e = *p as usize * 4;
            let got = [palette[e + 2], palette[e + 1], palette[e], palette[e + 3]];
            assert_eq!(got, px[i * 4..i * 4 + 4], "pixel {i} came back a different colour");
        }
    }

    #[test]
    fn a_palettised_image_never_indexes_past_its_tag() {
        // 0x80 is populated to 16, and no texture in the install indexes above 15. An image with
        // far more colours than that must still not be the first one that does.
        let (buf, entry) = blob(32, 32, fmt::P8_16, 1);
        let mut px = vec![0u8; 32 * 32 * 4];
        for (i, p) in px.chunks_exact_mut(4).enumerate() {
            p.copy_from_slice(&[(i * 7 % 256) as u8, (i * 13 % 256) as u8, (i * 29 % 256) as u8, 255]);
        }
        let out = replace_pixels(&buf, &entry, &px, 32, 32).expect("encode");
        assert!(out[..32 * 32].iter().all(|&i| i < 16), "an index past the tag's populated region");
    }

    #[test]
    fn the_whole_chain_is_written() {
        // Four levels of a 32×32 DXT1: if only the top one were encoded, the rest would still be
        // the zeroes the fixture was built with.
        let (buf, entry) = blob(32, 32, fmt::DXT1, 4);
        let out = replace_pixels(&buf, &entry, &quadrants(32, 32), 32, 32).expect("encode");
        let top = 32 * 32 / 2;
        let chain_end = top + 16 * 16 / 2 + 8 * 8 / 2 + 4 * 4 / 2;
        assert!(out[top..chain_end].iter().any(|&b| b != 0), "levels below the top were left empty");
    }

    /// A blob that is not the length its descriptor claims cannot be written back at all.
    ///
    /// The failure it prevents is silent and total: `relocate` records the replacement's length as
    /// the new `out_size` and leaves `header_from_end` alone, and the header sits at the difference
    /// of the two — so a blob one byte long in the wrong direction relocates into a pack whose
    /// header is read one byte off, and the texture decodes as noise.
    #[test]
    fn a_blob_that_is_not_its_declared_length_is_refused() {
        let (buf, entry) = blob(16, 16, fmt::RGBA8888, 1);
        let mut longer = buf.clone();
        longer.push(0);
        let px = quadrants(16, 16);
        assert!(matches!(
            replace_pixels(&longer, &entry, &px, 16, 16).expect_err("must refuse"),
            NfsError::BufferSizeMismatch { .. }
        ));
        let mut shorter = buf.clone();
        shorter.pop();
        assert!(replace_pixels(&shorter, &entry, &px, 16, 16).is_err());
        // And the exact length still goes through, so the check is about the length and not about
        // the buffer being suspicious.
        assert!(replace_pixels(&buf, &entry, &px, 16, 16).is_ok());
    }

    /// A header saying the image is nothing is refused rather than obeyed.
    ///
    /// Zero levels fill zero bytes exactly, so the chain's own exactness check has no complaint —
    /// and the palette is rewritten before the levels are, so obeying it would leave a palettised
    /// texture's old indices pointing into a new set of colours.
    #[test]
    fn an_image_size_of_zero_is_refused() {
        let (mut buf, entry) = blob(16, 16, fmt::P8, 1);
        let p = decode::header_at(entry.out_size as usize, entry.header_from_end as usize).unwrap();
        let before = buf.clone();
        buf[p + 0x14..p + 0x18].copy_from_slice(&0u32.to_le_bytes());
        let err = replace_pixels(&buf, &entry, &quadrants(16, 16), 16, 16).expect_err("must refuse");
        assert!(matches!(err, NfsError::CorruptArchive { .. }));
        // And with a real ImageSize the same blob goes through, so the refusal is about the zero.
        assert!(replace_pixels(&before, &entry, &quadrants(16, 16), 16, 16).is_ok());
    }

    #[test]
    fn a_differently_sized_image_is_refused_rather_than_written() {
        let (buf, entry) = blob(16, 16, fmt::RGBA8888, 1);
        let err = replace_pixels(&buf, &entry, &quadrants(8, 8), 8, 8).expect_err("must refuse");
        assert!(matches!(err, NfsError::BufferSizeMismatch { .. }));
    }

    #[test]
    fn an_image_size_that_is_not_whole_levels_is_refused() {
        let (mut buf, entry) = blob(16, 16, fmt::DXT1, 1);
        let p = decode::header_at(entry.out_size as usize, entry.header_from_end as usize).unwrap();
        // One byte more than the top mip, and no level is one byte.
        buf[p + 0x14..p + 0x18].copy_from_slice(&(16u32 * 16 / 2 + 1).to_le_bytes());
        let err = replace_pixels(&buf, &entry, &quadrants(16, 16), 16, 16).expect_err("must refuse");
        assert!(matches!(err, NfsError::CorruptArchive { .. }));
    }

    #[test]
    fn a_header_that_fails_its_own_check_is_refused() {
        let (mut buf, mut entry) = blob(16, 16, fmt::RGBA8888, 1);
        entry.hash = AssetHash(0xDEAD_BEEF);
        let err = replace_pixels(&buf, &entry, &quadrants(16, 16), 16, 16).expect_err("must refuse");
        assert!(matches!(err, NfsError::CorruptArchive { .. }));
        // And the same refusal when the header itself is the thing that moved.
        buf.truncate(4);
        assert!(replace_pixels(&buf, &entry, &quadrants(16, 16), 16, 16).is_err());
    }

    #[test]
    fn two_runs_over_one_image_agree() {
        // The palette comes out of a HashMap, whose order is randomised per process; two runs that
        // disagreed would make a written pack unreproducible.
        let (buf, entry) = blob(32, 32, fmt::P8, 1);
        let mut px = vec![0u8; 32 * 32 * 4];
        for (i, p) in px.chunks_exact_mut(4).enumerate() {
            p.copy_from_slice(&[(i % 256) as u8, (i * 3 % 256) as u8, (i * 5 % 256) as u8, 255]);
        }
        let a = replace_pixels(&buf, &entry, &px, 32, 32).expect("encode");
        let b = replace_pixels(&buf, &entry, &px, 32, 32).expect("encode");
        assert_eq!(a, b);
    }
}
